var taek_data = [
    {	"name" : "white", 
	"kup" : "10th",
	"col" : ['#FFFFFF','#FFFFFF','#FFFFFF'],
	"words" : [
	    { "Training Hall" : [ "Dojang" ] },
	    { "Training Suit" : ["Dobok"] },
	    { "Instructor" : ["Sabum"] },
	    { "Belt" : ["Ti"] },
	    { "Student" : ["Jeja"] },
	    { "Inner" : ["An"] },
	    { "Outer" : ["Batak"] },
	    { "Press Ups" : ["Momtong Bachia"] },
	    { "Attention" : ["Charyot"] },
	    { "Bow" : ["Kyong-Yee"] },
	    { "Ready" : ["Chunbi"] },
	    { "Start" : ["Si-jak"] },
	    { "Stop" : ["Goman"] },
	    { "Return To Ready Stance" : ["Barrol"] },
	    { "Dismiss" : ["Haessan"] },
	    { "Forward" : ["Apro Kaggi"] },
	    { "Backward" : ["Dwiyro Kaggi"] },
	    { "About Turn" : ["Dwiyro Torro"] },
	    { "One" : ["Hanna"] },
	    { "Two" : ["Dool"] },
	    { "Three" : ["Set"] },
	    { "Four" : ["Net"] },
	    { "Five" : ["Dasaul"] },
	    { "Six" : ["Yosaul"] },
	    { "Seven" : ["Ilgop"] },
	    { "Eight" : ["Yodoll"] },
	    { "Nine" : ["Ahop"] },
	    { "Ten" : ["Yoll"] },
	    { "Low" : ["Najunde"] },
	    { "Middle" : ["Kaunde"] },
	    { "High" : ["Nopude"] },
	    { "Forfist" : ["Ap Joomuk"] },
	    { "Forearm" : ["Palmok"] },
	    { "Inner Forearm" : ["An Palmok"] },
	    { "Outer Forearm" : ["Batak Palmok"] },
	    { "Attention Stance" : ["Charyot Sogi"] },
	    { "Parallel Stance" : ["Narani Sogi"] },
	    { "Sitting Stance" : ["Annun Sogi"] },
	    { "Walking Stance" : ["Gunning Sogi"] },
	    { "Inner Forearm block" : ["An Palmok Magki"] },
	    { "Outer Forearm block" : ["Batak Palmok Makgi"] },
	    { "Front Rising Kick" : ["Ap Cha Olligi"] },
	    { "Side Rising Kick" : ["Yop Cha Olligi"] },
	    { "Obverse Punch" : ["Baro Jirugi"] },
	    { "Reverse Punch" : ["Bandae Jirugi"] },
	    { "4 Directional Punch" : ["Sajo Jirugi"] },
	    { "White" : ["Innocence"] },
	    { "Block" : ["Makgi"] },
	    { "Punch" : ["Jirugi"] },
	    { "Stance" : ["Sogi"] }
	]
    },
    {	"name" : "yellow_tag",
	"kup" : "9th",
	"col" : ['#FFFFFF','#FFFF00','#FFFFFF'],
	"words" : [
	    { "Left" : ["Wen"] },
	    { "Right" : ["Orun"] },
	    { "Pattern" : ["Tul"] },
	    { "Ball of Foot" : ["Ap Kumchi"] },
	    { "Foot Sward" : ["Balkal"] },
	    { "Head" : ["Mori"] },
	    { "L Stance" : ["Niunja Sogi"] },
	    { "Rising Block" : ["Chookyo Magki"] },
	    { "Forearm Guarding Block" : ["Palmok Daebi Magki"] },
	    { "Kick" : ["Chagi"] },
	    { "Double Punch" : ["Doo Jirugi"] },
	    { "Front Snap Kick" : ["Ap Cha Busigi"] },
	    { "Knife Hand Strike" : ["Sonkal Taerigi"] },
	    { "Heaven and Earth" : ["Chon-Ji","19 Moves"] },
	]
    },
    {	"name" : "yellow",
	"kup" : "8th",
	"col" : ['#FFFF00','#FFFF00','#FFFF00'],
	"words" : [
	    { "Inward" : ["Anaero"] },
	    { "Outward" : ["Bakaero"] },
	    { "Downward" : ["Naeryo"] },
	    { "Half facing" : ["Ban Mom"] },
	    { "Full facing" : ["On Mom"] },
	    { "Side facing" : ["Yop Mom"] },
	    { "Palm" : ["Sonbadak"] },
	    { "Knifehand" : ["Sonkal"] },
	    { "Backfist" : ["Dung Joomuk"] },
	    { "Knifehand guarding block" : ["Sonkal Daebi Magki"] },
	    { "Twin forearm block" : ["Sang Palmok Magki"] },
	    { "Outer forearm inward block" : ["Bakat Palmok Anaero Magki"] },
	    { "Backfist front downward strike" : ["Dung Joomuk Ap Naeryo Taerigi"] },
	    { "Turning Kick" : ["Dollyo Chagi"] },
	    { "Dan-Gun" : ["Founder of Korea","2333BC","21 Moves"] },
	    { "Three step sparring" : ["Sambo Matsoki"] },
	    { "Green" : ["Growth"] },
	]
    }
];
